model_type: tuna

stages:
  - stage_id: 0
    model_stage: diffusion
    stage_type: diffusion
    input_sources: []
    final_output: true
    final_output_type: image
    engine_args:
      model_class_name: TunaExternalPipeline
      trust_remote_code: true
      distributed_executor_backend: mp
      custom_pipeline_args:
        variant: none_encoder
    runtime:
      devices: "0"
    default_sampling_params:
      seed: 42
      num_inference_steps: 50
      guidance_scale: 3.0
