[default.extend-words]
ba = "ba"
thw = "thw"
nin = "nin"
vai = "vai"
ue = "ue"
thi = "thi"
arange = "arange"
fullset = "fullset"
CANN = "CANN"
seeked = "seeked"
nd = "nd"
nothink = "nothink"
NOTHINK = "NOTHINK"
tockens = "tockens"
Vai = "Vai"
semantics = "semantics"
updator = "updator"
cann = "cann"

[default.extend-identifiers]
ono_anna = "ono_anna"
temperal_downsample = "temperal_downsample"
byt5 = "byt5"
byt5_config = "byt5_config"
byt5_mapper_config = "byt5_mapper_config"
byt5_max_length = "byt5_max_length"
byt5_ckpt_path = "byt5_ckpt_path"
mock_byt5_tok = "mock_byt5_tok"
byt5_model = "byt5_model"
byt5_mapper = "byt5_mapper"
ein = "ein"
