# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM-Omni project
"""Real safetensors/JSON CPU imports; no vLLM, msModelSlim, NPU or model download.

Standalone: pytest --confcutdir=tests/diffusion/quantization <this file>
The file-based import intentionally exercises the independently executable tool.
"""

import importlib.util
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest
import torch
from safetensors import safe_open
from safetensors.torch import load_file, save_file

pytestmark = [pytest.mark.core_model, pytest.mark.diffusion, pytest.mark.cpu]
TOOL = Path(__file__).resolve().parents[3] / "vllm_omni/quantization/tools/merge_mxfp4_checkpoint.py"
SPEC = importlib.util.spec_from_file_location("single_mxfp4_import_tool", TOOL)
assert SPEC is not None and SPEC.loader is not None
converter = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = converter
SPEC.loader.exec_module(converter)

QTYPE = "W4A4_MXFP4"
EXPERTS = ("high_noise_model", "low_noise_model")
TARGETS = ("transformer", "transformer_2")
QUANT_FILE = "quant_model_weight_w4a4_mxfp4.safetensors"
DESC_FILE = "quant_model_description_w4a4_mxfp4.json"


def _json(path, value):
    path.write_text(json.dumps(value), encoding="utf-8")


def _fixture(tmp_path, smooth=False):
    """Tiny native Wan names, official uint8 export packing and two distinct experts."""
    original, quant, output = (tmp_path / name for name in ("original", "quant", "output"))
    original.mkdir()
    quant.mkdir()
    _json(
        original / "model_index.json",
        {
            "_class_name": "WanPipeline",
            "transformer": ["diffusers", "WanTransformer3DModel"],
            "transformer_2": ["diffusers", "WanTransformer3DModel"],
        },
    )
    (original / "tokenizer").mkdir()
    (original / "tokenizer/vocab.txt").write_text("unchanged scaffold", encoding="utf-8")
    # Source/target pairs are independently specified, not generated by production remapping.
    pairs = [
        ("blocks.0.self_attn.q", "blocks.0.attn1.to_q"),
        ("blocks.0.self_attn.k", "blocks.0.attn1.to_k"),
        ("blocks.0.self_attn.v", "blocks.0.attn1.to_v"),
        ("blocks.0.self_attn.o", "blocks.0.attn1.to_out.0"),
        ("blocks.0.ffn.0", "blocks.0.ffn.net.0.proj"),
        ("blocks.0.ffn.2", "blocks.0.ffn.net.2"),
        ("blocks.0.cross_attn.q", "blocks.0.attn2.to_q"),
    ]
    float_pairs = [
        ("blocks.1.self_attn.q", "blocks.1.attn1.to_q"),
        ("blocks.1.self_attn.k", "blocks.1.attn1.to_k"),
        ("blocks.1.self_attn.v", "blocks.1.attn1.to_v"),
        ("blocks.1.self_attn.o", "blocks.1.attn1.to_out.0"),
        ("blocks.1.ffn.0", "blocks.1.ffn.net.0.proj"),
        ("blocks.1.ffn.2", "blocks.1.ffn.net.2"),
        ("blocks.1.cross_attn.k", "blocks.1.attn2.to_k"),
        ("head.head", "proj_out"),
        ("time_embedding.0", "condition_embedder.time_embedder.linear_1"),
    ]
    for index, (source, target) in enumerate(zip(EXPERTS, TARGETS)):
        src, base = quant / source, original / target
        src.mkdir()
        base.mkdir()
        _json(base / "config.json", {"_class_name": "WanTransformer3DModel", "num_layers": 2})
        raw, desc, bf16 = {}, {"model_quant_type": QTYPE}, {}
        # Each row covers both signs and every E2M1 value, including negative zero.
        pattern = [0x10, 0x32, 0x54, 0x76, 0x98, 0xBA, 0xDC, 0xFE]
        if index:
            pattern = list(reversed(pattern))
        for native, diffusers in pairs:
            prefix = native + (".linear" if smooth else "")
            raw[prefix + ".weight"] = torch.tensor(pattern * 16, dtype=torch.uint8).reshape(4, 32)
            raw[prefix + ".weight_scale"] = torch.tensor([126, 128] * 4, dtype=torch.uint8).reshape(4, 2)
            raw[prefix + ".bias"] = torch.arange(4, dtype=torch.float32) + index
            desc[prefix + ".weight"] = desc[prefix + ".weight_scale"] = QTYPE
            desc[prefix + ".bias"] = "FLOAT"
            bf16[diffusers + ".weight"] = torch.full((4, 64), 9, dtype=torch.bfloat16)
            bf16[diffusers + ".bias"] = torch.full((4,), 9, dtype=torch.bfloat16)
            if smooth:
                raw[native + ".div.mul_scale"] = torch.linspace(0.5, 1.5, 64)
                desc[native + ".div.mul_scale"] = "FLOAT"
        for native, diffusers in float_pairs:
            raw[native + ".weight"] = torch.full((4, 64), index + 3, dtype=torch.bfloat16)
            bf16[diffusers + ".weight"] = torch.full((4, 64), 9, dtype=torch.bfloat16)
            desc[native + ".weight"] = "FLOAT"
        for native, diffusers in (
            ("blocks.0.norm2.weight", "blocks.0.norm3.weight"),
            ("blocks.0.modulation", "blocks.0.scale_shift_table"),
        ):
            raw[native] = torch.ones(4, dtype=torch.bfloat16)
            bf16[diffusers] = torch.zeros(4, dtype=torch.bfloat16)
            desc[native] = "FLOAT"
        # Non-Linear scaffold can come only from the original without quant metadata.
        bf16["patch_embedding.weight"] = torch.zeros((4, 16, 1, 2, 2), dtype=torch.bfloat16)
        save_file(bf16, str(base / "diffusion_pytorch_model.safetensors"))
        save_file(raw, str(src / QUANT_FILE))
        _json(src / DESC_FILE, desc)
    return original, quant, output


def _convert(paths, **kwargs):
    return converter.repack("Wan2.2-T2V-A14B", *paths, **kwargs)


def _read_output(directory):
    result = {}
    for path in directory.glob("*.safetensors"):
        result.update(load_file(str(path)))
    return result


def _edit(paths, mutate, expert=1):
    directory = paths[1] / EXPERTS[expert]
    raw = load_file(str(directory / QUANT_FILE))
    desc = json.loads((directory / DESC_FILE).read_text(encoding="utf-8"))
    mutate(raw, desc)
    save_file(raw, str(directory / QUANT_FILE))
    _json(directory / DESC_FILE, desc)


@pytest.mark.parametrize("smooth", [False, True])
def test_real_two_expert_conversion_preserves_values_scales_and_policy(tmp_path, smooth):
    paths = _fixture(tmp_path, smooth)
    report = _convert(paths, max_shard_bytes=2048)
    original, quant, output = paths
    expected = [0, 0.5, 1, 1.5, 2, 3, 4, 6, -0.0, -0.5, -1, -1.5, -2, -3, -4, -6]
    for index, target in enumerate(TARGETS):
        state = _read_output(output / target)
        config = json.loads((output / target / "config.json").read_text())
        policy = config["quantization_config"]
        assert policy["quant_method"] == "mxfp4"
        assert policy["is_checkpoint_mxfp4_serialized"] is True
        assert policy["require_smooth_scale"] is smooth
        assert "is_checkpoint_serialized" not in policy
        assert {
            "blocks.1.attn1.to_qkv",
            "blocks.1.attn1.to_out",
            "blocks.1.ffn.net_0.proj",
            "blocks.1.ffn.net_2",
            "blocks.1.attn2.to_k",
            "proj_out",
            "condition_embedder.time_embedder.linear_1",
        } <= set(policy["ignored_layers"])
        assert "blocks.0.attn1.to_qkv" not in policy["ignored_layers"]
        row = expected if not index else sum([expected[i : i + 2] for i in range(14, -1, -2)], [])
        expected_weight = torch.tensor(row * 16, dtype=torch.bfloat16).reshape(4, 64)
        weight = state["blocks.0.attn1.to_q.weight"]
        assert weight.dtype == torch.bfloat16
        assert torch.equal(weight, expected_weight)
        assert torch.equal(torch.signbit(weight), torch.signbit(expected_weight))
        raw = load_file(str(quant / EXPERTS[index] / QUANT_FILE))
        prefix = "blocks.0.self_attn.q" + (".linear" if smooth else "")
        scale = state["blocks.0.attn1.to_q.weight_scale"]
        assert scale.dtype == torch.uint8
        assert torch.equal(scale, raw[prefix + ".weight_scale"])
        assert torch.equal(state["blocks.0.attn1.to_q.bias"], raw[prefix + ".bias"])
        assert bool((state["blocks.1.attn1.to_q.weight"] == index + 3).all())
        assert bool((state["blocks.0.norm3.weight"] == 1).all())
        if smooth:
            assert torch.equal(state["blocks.0.attn1.to_q.mul_scale"], raw["blocks.0.self_attn.q.div.mul_scale"])
        else:
            assert not any(name.endswith("mul_scale") for name in state)
            assert "does not validate Smooth" in report["experts"][target]["smooth"]
        assert not any("dual_scale" in name or "w4a8_weight" in name for name in state)
        index_json = json.loads((output / target / "diffusion_pytorch_model.safetensors.index.json").read_text())
        assert set(index_json["weight_map"]) == set(state)
        assert len(set(index_json["weight_map"].values())) > 1
        for name, shard in index_json["weight_map"].items():
            with safe_open(str(output / target / shard), framework="pt") as archive:
                assert name in archive.keys()
    assert (output / "tokenizer/vocab.txt").read_bytes() == (original / "tokenizer/vocab.txt").read_bytes()
    assert report == json.loads((output / "mxfp4_conversion_report.json").read_text(encoding="utf-8"))
    assert report["producer_version"].startswith("unknown")
    assert "not verified" in report["algorithm_provenance"]


@pytest.mark.parametrize(
    "label", ["W4A4_MXFP4_DUALSCALE", "W8A8_MXFP8", "W8A8", "W4A8_MXFP", "W4A4_MXFP", "W4A4_MXFP4_NEW", None, {}]
)
def test_unknown_or_mixed_labels_fail_closed(tmp_path, label):
    paths = _fixture(tmp_path)
    _edit(paths, lambda raw, desc: desc.update({"blocks.0.ffn.0.weight": label}))
    with pytest.raises(ValueError, match="不支持.*quant label"):
        _convert(paths)
    assert not paths[2].exists()


@pytest.mark.parametrize(
    "case,match",
    [
        ("missing_weight", "缺少量化 tensor"),
        ("missing_scale", "缺少量化 tensor"),
        ("missing_weight_label", "缺量化描述"),
        ("omitted_layer", "Linear 缺量化描述"),
        ("wrong_weight_dtype", "weight packing"),
        ("wrong_weight_shape", "weight packing"),
        ("wrong_scale_dtype", "weight_scale 必须"),
        ("wrong_scale_shape", "weight_scale 必须"),
        ("scale_nan", "E8M0 NaN"),
        ("dual_scale", "无原模型映射"),
        ("orphan_scale", "孤立/非法 weight_scale"),
        ("missing_bias", "缺导出 bias"),
        ("wrong_bias_shape", "FLOAT tensor dtype/shape"),
        ("nan_bias", "bias 必须"),
        ("global_dual", "model_quant_type"),
        ("missing_global", "model_quant_type"),
        ("fa_metadata", "不支持"),
        ("rotation_float", "不支持"),
        ("unknown_float", "不支持"),
        ("int_float", "FLOAT tensor dtype/shape"),
        ("wrong_group", "group_size"),
        ("partial_qkv", "QKV 不允许部分"),
    ],
)
def test_malformed_real_checkpoint_fails_without_publishing(tmp_path, case, match):
    paths = _fixture(tmp_path)

    def mutate(raw, desc):
        key = "blocks.0.ffn.0.weight"
        scale = "blocks.0.ffn.0.weight_scale"
        bias = "blocks.0.ffn.0.bias"
        if case == "missing_weight":
            del raw[key]
        elif case == "missing_scale":
            del raw[scale]
        elif case == "missing_weight_label":
            del desc[key]
        elif case == "omitted_layer":
            for name in (key, scale, bias):
                del raw[name], desc[name]
        elif case == "wrong_weight_dtype":
            raw[key] = raw[key].to(torch.int8)
        elif case == "wrong_weight_shape":
            raw[key] = raw[key][:, :16].contiguous()
        elif case == "wrong_scale_dtype":
            raw[scale] = raw[scale].float()
        elif case == "wrong_scale_shape":
            raw[scale] = raw[scale].reshape(4, 1, 2)
        elif case == "scale_nan":
            raw[scale][0, 0] = 255
        elif case in ("dual_scale", "orphan_scale", "rotation_float", "unknown_float"):
            name = {
                "dual_scale": "blocks.0.ffn.0.weight_dual_scale",
                "orphan_scale": "blocks.1.ffn.0.weight_scale",
                "rotation_float": "blocks.0.self_attn.q.rotation",
                "unknown_float": "other_recipe.cache",
            }[case]
            raw[name] = torch.ones(4)
            desc[name] = "FLOAT"
        elif case == "missing_bias":
            del raw[bias], desc[bias]
        elif case == "wrong_bias_shape":
            raw[bias] = torch.zeros(5)
        elif case == "nan_bias":
            raw[bias][0] = float("nan")
        elif case == "global_dual":
            desc["model_quant_type"] = "W4A4_MXFP4_DUALSCALE"
        elif case == "missing_global":
            del desc["model_quant_type"]
        elif case == "fa_metadata":
            desc["blocks.0.self_attn.quant_type"] = "MXFP4_DYNAMIC"
        elif case == "int_float":
            raw["head.head.weight"] = raw["head.head.weight"].to(torch.int8)
        elif case == "wrong_group":
            desc["group_size"] = 64
        elif case == "partial_qkv":
            name = "blocks.0.self_attn.q"
            raw[name + ".weight"] = torch.zeros((4, 64), dtype=torch.bfloat16)
            desc[name + ".weight"] = "FLOAT"
            del raw[name + ".weight_scale"], desc[name + ".weight_scale"]

    _edit(paths, mutate)
    with pytest.raises(ValueError, match=match):
        _convert(paths)
    assert not paths[2].exists()
    assert not list(tmp_path.glob(".mxfp4-import-*"))


@pytest.mark.parametrize(
    "case,match",
    [
        ("missing", "缺少 mul_scale"),
        ("undeclared", "必须有.*mul_scale"),
        ("shape", "mul_scale 必须为浮点"),
        ("dtype", "mul_scale 必须为浮点"),
        ("nan", "有限且正"),
        ("zero", "有限且正"),
        ("negative", "有限且正"),
        ("different_qkv", "QKV mul_scale 必须完全一致"),
        ("partial", "部分 Smooth"),
    ],
)
def test_smooth_contract_is_strict(tmp_path, case, match):
    paths = _fixture(tmp_path, smooth=True)

    def mutate(raw, desc):
        key = "blocks.0.self_attn.q.div.mul_scale"
        if case == "missing":
            del raw[key]
        elif case == "undeclared":
            del raw[key], desc[key]
        elif case == "shape":
            raw[key] = raw[key].reshape(1, 64)
        elif case == "dtype":
            raw[key] = raw[key].to(torch.int32)
        elif case in ("nan", "zero", "negative", "different_qkv"):
            raw[key][0] = {"nan": float("nan"), "zero": 0, "negative": -1, "different_qkv": 2}[case]
        elif case == "partial":
            del raw[key], desc[key]
            for attr in ("weight", "weight_scale", "bias"):
                name = "blocks.0.self_attn.q.linear." + attr
                raw[name.replace(".linear", "")] = raw.pop(name)
                desc[name.replace(".linear", "")] = desc.pop(name)

    _edit(paths, mutate)
    with pytest.raises(ValueError, match=match):
        _convert(paths)
    assert not paths[2].exists()


def test_require_smooth_rejects_valid_unsmoothed_export(tmp_path):
    paths = _fixture(tmp_path)
    with pytest.raises(ValueError, match="声明 Smooth"):
        _convert(paths, require_smooth_scale=True)
    assert not paths[2].exists()


def test_explicit_float_can_use_original_but_quantized_never_can(tmp_path):
    paths = _fixture(tmp_path)
    _edit(paths, lambda raw, desc: raw.pop("head.head.weight"))
    report = _convert(paths)
    assert report["experts"]["transformer_2"]["original_bf16_for_explicit_float"] == ["proj_out.weight"]
    assert bool((_read_output(paths[2] / "transformer_2")["proj_out.weight"] == 9).all())


def test_sharded_export_and_expert_specific_bf16_policy(tmp_path):
    paths = _fixture(tmp_path)

    def make_float(raw, desc):
        prefix = "blocks.0.ffn.0"
        raw[prefix + ".weight"] = torch.ones((4, 64), dtype=torch.bfloat16)
        desc[prefix + ".weight"] = "FLOAT"
        del raw[prefix + ".weight_scale"], desc[prefix + ".weight_scale"]

    _edit(paths, make_float)
    for expert in EXPERTS:
        directory = paths[1] / expert
        raw = load_file(str(directory / QUANT_FILE))
        names = sorted(raw)
        shards = ["quant_model_weight-00001.safetensors", "quant_model_weight-00002.safetensors"]
        mapping = {}
        for number, shard in enumerate(shards):
            subset = {name: raw[name] for name in names[number::2]}
            save_file(subset, str(directory / shard))
            mapping.update({name: shard for name in subset})
        (directory / QUANT_FILE).unlink()
        _json(directory / "quant_model_weight.safetensors.index.json", {"weight_map": mapping})
        (directory / DESC_FILE).rename(directory / "quant_model_description.json")
    report = _convert(paths)
    assert "blocks.0.ffn.net_0.proj" not in report["experts"]["transformer"]["ignored_layers"]
    assert "blocks.0.ffn.net_0.proj" in report["experts"]["transformer_2"]["ignored_layers"]


def test_source_key_collision_is_rejected(tmp_path):
    paths = _fixture(tmp_path)

    def collide(raw, desc):
        raw["blocks.0.ffn.0.linear.weight"] = raw["blocks.0.ffn.0.weight"].clone()
        desc["blocks.0.ffn.0.linear.weight"] = QTYPE

    _edit(paths, collide)
    with pytest.raises(ValueError, match="重命名冲突"):
        _convert(paths)


@pytest.mark.parametrize("case", ["header", "nested_rank"])
def test_extra_format_metadata_is_not_discarded(tmp_path, case):
    paths = _fixture(tmp_path)
    directory = paths[1] / EXPERTS[1]
    if case == "header":
        path = directory / QUANT_FILE
        raw = load_file(str(path))
        save_file(raw, str(path), metadata={"rotation": "quarot"})
    else:
        (directory / "rank_0").mkdir()
    with pytest.raises(ValueError, match="不支持"):
        _convert(paths)
    assert not paths[2].exists()


@pytest.mark.parametrize("value", [1e-44, 3.402823466e38])
def test_smooth_must_remain_finite_positive_in_runtime_dtype(tmp_path, value):
    paths = _fixture(tmp_path, smooth=True)
    _edit(paths, lambda raw, desc: raw["blocks.0.ffn.0.div.mul_scale"].fill_(value))
    with pytest.raises(ValueError, match="有限且正"):
        _convert(paths)


def test_all_e2m1_codes_and_nibble_order_via_real_files(tmp_path):
    paths = _fixture(tmp_path)

    # Two independent source tensors together cover all 256 possible packed bytes.
    def all_codes(raw, desc):
        raw["blocks.0.ffn.0.weight"] = torch.arange(128, dtype=torch.uint8).reshape(4, 32)
        raw["blocks.0.ffn.2.weight"] = torch.arange(128, 256, dtype=torch.uint8).reshape(4, 32)

    _edit(paths, all_codes)
    _convert(paths)
    result = _read_output(paths[2] / "transformer_2")

    # Scalar E2M1 definition is independent of the production lookup table.
    def scalar(code):
        exponent, mantissa = (code >> 1) & 3, code & 1
        magnitude = mantissa / 2 if exponent == 0 else (1 + mantissa / 2) * 2 ** (exponent - 1)
        return -magnitude if code & 8 else magnitude

    for target, start in (("blocks.0.ffn.net.0.proj.weight", 0), ("blocks.0.ffn.net.2.weight", 128)):
        expected = torch.tensor(
            [scalar(code) for byte in range(start, start + 128) for code in (byte & 15, byte >> 4)],
            dtype=torch.bfloat16,
        ).reshape(4, 64)
        assert torch.equal(result[target], expected)
        assert torch.equal(torch.signbit(result[target]), torch.signbit(expected))


@pytest.mark.parametrize(
    "case",
    [
        "description",
        "duplicate_description",
        "duplicate_json_key",
        "duplicate_tensor",
        "index",
        "rotation_sidecar",
        "second_expert",
        "output_exists",
        "missing_qkv",
    ],
)
def test_file_level_failures_are_closed(tmp_path, case):
    paths = _fixture(tmp_path)
    source = paths[1] / EXPERTS[1]
    if case == "description":
        (source / DESC_FILE).unlink()
    elif case == "duplicate_description":
        (source / "quant_model_description.json").write_bytes((source / DESC_FILE).read_bytes())
    elif case == "duplicate_json_key":
        path = source / DESC_FILE
        text = path.read_text()
        path.write_text(text[:-1] + ', "model_quant_type": "W4A4_MXFP4"}')
    elif case == "duplicate_tensor":
        (source / "quant_model_weight-extra.safetensors").write_bytes((source / QUANT_FILE).read_bytes())
    elif case == "index":
        _json(source / "quant_model_weight.safetensors.index.json", {"weight_map": {"missing": QUANT_FILE}})
    elif case == "rotation_sidecar":
        (paths[1] / "quarot_config.json").write_text("{}")
    elif case == "second_expert":
        (source / QUANT_FILE).unlink()
    elif case == "output_exists":
        paths[2].mkdir()
        (paths[2] / "sentinel").write_text("keep")
    elif case == "missing_qkv":

        def remove(raw, desc):
            for name in list(desc):
                if name.startswith("blocks.0.self_attn.k."):
                    desc.pop(name)
                    raw.pop(name)

        _edit(paths, remove)
    with pytest.raises(ValueError):
        _convert(paths)
    if case == "output_exists":
        assert (paths[2] / "sentinel").read_text() == "keep"
    else:
        assert not paths[2].exists()


def test_cli_uses_real_files_without_inference_dependencies(tmp_path):
    paths = _fixture(tmp_path, smooth=True)
    result = subprocess.run(
        [
            sys.executable,
            str(TOOL),
            "--original-model",
            str(paths[0]),
            "--quant-path",
            str(paths[1]),
            "--output-path",
            str(paths[2]),
            "--require-smooth-scale",
            "--max-shard-size-mb",
            "1",
        ],
        text=True,
        encoding="utf-8",
        capture_output=True,
        env={**os.environ, "PYTHONUTF8": "1"},
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert json.loads(result.stdout)["source_contract"] == converter.SOURCE_CONTRACT
    assert (paths[2] / "transformer_2/config.json").is_file()


@pytest.mark.parametrize("native", ["head.head", "time_embedding.0"])
def test_conversion_rejects_quantized_float_only_root_modules(tmp_path, native):
    paths = _fixture(tmp_path)

    def quantize_root(raw, desc):
        raw[native + ".weight"] = torch.ones((4, 32), dtype=torch.uint8)
        raw[native + ".weight_scale"] = torch.full((4, 2), 128, dtype=torch.uint8)
        desc[native + ".weight"] = desc[native + ".weight_scale"] = QTYPE

    _edit(paths, quantize_root)
    with pytest.raises(ValueError, match="not supported by the Wan Linear method"):
        _convert(paths)
    assert not paths[2].exists()
