steps:
  - label: "Simple Unit Test"
    commands:
      - ".buildkite/scripts/simple_test.sh"
    agents:
      queue: "cpu_queue_premerge"
  - label: "Diffusion Model Test"
    source_file_dependencies:
      - "vllm_omni/diffusion/"
      - "vllm_omni/entrypoints"
    commands:
      - ".buildkite/scripts/diffusion_model_test.sh"
    agents:
      queue: "gpu_1_queue" # g6.4xlarge instance on AWS, has 1 L4 GPU
