steps:
  - label: ":docker: Build NPU Image"
    key: image-build
    agents:
      queue: "linux-aarch64-a2b3-gy006-test"
    plugins:
      - docker#v5.2.0:
          image: "docker:24.0"
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    command: |
      docker build -t vllm-omni-ci-npu -f ./docker/Dockerfile_test.npu .

  - label: "Upload Test Pipeline"
    depends_on: image-build
    agents:
      queue: "linux-aarch64-a2b3-gy006-test"
    command: |
      if [[ "${BUILDKITE_BRANCH}" == "main" ]]; then
        echo "--- 上传 merge 测试 pipeline"
        buildkite-agent pipeline upload .buildkite/test-npu-merge.yaml
      else
        echo "--- 上传 ready 测试 pipeline"
        buildkite-agent pipeline upload .buildkite/test-npu-ready.yaml
      fi