steps:
  - label: "Simple Unit Test"
    commands:
      - ".buildkite/scripts/setup_env.sh"
      - pytest -v -s tests/test_omni_llm.py
    agents:
      queue: "cpu_queue_premerge"
  - label: "Diffusion Model Test"
    commands:
      - ".buildkite/scripts/setup_env.sh"
      - pytest -s -v tests/test_diffusion_model.py
    agents:
      queue: "gpu_1_queue" # g6.4xlarge instance on AWS, has 1 L4 GPU
