steps:
  - label: ":docker: Build image"
    key: image-build
    commands:
      - "docker build -f docker/Dockerfile.rocm -t vllm-omni-rocm ."
    agents:
      queue: "cpu_queue_premerge_us_east_1"

  - label: "Simple Unit Test"
    commands:
      - ".buildkite/scripts/simple_test.sh"
    agents:
      queue: "cpu_queue_premerge"
