env:
  VLLM_WORKER_MULTIPROC_METHOD: spawn
  HF_HUB_DOWNLOAD_TIMEOUT: 300
  HF_HUB_ETAG_TIMEOUT: 60

steps:
  - label: "Unified tests with merged coverage"
    depends_on: upload-ready-pipeline
    commands:
      - |
        timeout 20m pytest -v -s -m 'core_model and cpu' \
        --cov=vllm_omni --cov-branch --cov-report=
      
        timeout 10m pytest -v -s -m 'core_model and cuda and L4 and not distributed_cuda' \
        --cov=vllm_omni --cov-branch --cov-append --cov-report= \
        --ignore=tests/e2e --ignore=tests/engine/test_async_omni_engine_abort.py
      
        timeout 10m pytest -v -s -m 'core_model and cuda and L4 and distributed_cuda' \
        --cov=vllm_omni --cov-branch --cov-append --cov-report=
      
        coverage html
        coverage xml
        coverage report -m
    agents:
      queue: "gpu_4_queue"
    plugins:
      - docker#v5.2.0:
          image: public.ecr.aws/q9t5s3a7/vllm-ci-test-repo:$BUILDKITE_COMMIT
          always-pull: true
          propagate-environment: true
          environment:
            - "HF_HOME=/fsx/hf_cache"
            - "HF_TOKEN"
          volumes:
            - "/fsx/hf_cache:/fsx/hf_cache"
  
