steps:

- label: "Diffusion Model Test"
  timeout_in_minutes: 15
  agent_pool: mi325_2
  depends_on: image-build
  mirror_hardwares: [amdexperimental, amdproduction, amdtentative]
  grade: Blocking
  source_file_dependencies:
  - ./
  commands:
    - pytest -s -v tests/e2e/offline_inference/test_t2i_model.py