# .buildkite/pipeline-npu-merge.yaml
# L3: NPU tests triggered on merge to main
steps:
  - group: "NPU Tests (L3 - Merge)"
    steps:
      - label: "NPU A2B3: Basic Test (1 card)"
        agents:
          queue: "linux-aarch64-a2b3-gy006-test"
        plugins:
          - kubernetes#v1.0:
              image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
              podSpec:
                nodeSelector:
                  kubernetes.io/arch: arm64
                containers:
                  - name: test
                    volumeMounts:
                      - name: davinci0
                        mountPath: /dev/davinci0
                      - name: davinci-manager
                        mountPath: /dev/davinci_manager
                      - name: devmm-svm
                        mountPath: /dev/devmm_svm
                      - name: hisi-hdc
                        mountPath: /dev/hisi_hdc
                      - name: ascend-dcmi
                        mountPath: /usr/local/dcmi
                      - name: ascend-npu-smi
                        mountPath: /usr/local/bin/npu-smi
                      - name: ascend-driver-lib
                        mountPath: /usr/local/Ascend/driver/lib64
                      - name: ascend-driver-version
                        mountPath: /usr/local/Ascend/driver/version.info
                      - name: ascend-install-info
                        mountPath: /etc/ascend_install.info
                volumes:
                  - name: davinci0
                    hostPath:
                      path: /dev/davinci0
                  - name: davinci-manager
                    hostPath:
                      path: /dev/davinci_manager
                  - name: devmm-svm
                    hostPath:
                      path: /dev/devmm_svm
                  - name: hisi-hdc
                    hostPath:
                      path: /dev/hisi_hdc
                  - name: ascend-dcmi
                    hostPath:
                      path: /usr/local/dcmi
                  - name: ascend-npu-smi
                    hostPath:
                      path: /usr/local/bin/npu-smi
                  - name: ascend-driver-lib
                    hostPath:
                      path: /usr/local/Ascend/driver/lib64
                  - name: ascend-driver-version
                    hostPath:
                      path: /usr/local/Ascend/driver/version.info
                  - name: ascend-install-info
                    hostPath:
                      path: /etc/ascend_install.info
        command: |
          source /usr/local/Ascend/ascend-toolkit/set_env.sh
          source /usr/local/Ascend/nnal/atb/set_env.sh
          pip install -e .
          VLLM_USE_MODELSCOPE=True pytest -s -v tests/e2e/offline_inference/test_qwen2_5_omni.py
        timeout_in_minutes: 60
        soft_fail: true

      - label: "NPU A2B3: Qwen2.5-Omni Offline Inference (2 cards)"
        agents:
          queue: "linux-aarch64-a2b3-gy006-test"
        plugins:
          - kubernetes#v1.0:
              image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
              podSpec:
                nodeSelector:
                  kubernetes.io/arch: arm64
                containers:
                  - name: test
                    volumeMounts:
                      - name: davinci0
                        mountPath: /dev/davinci0
                      - name: davinci1
                        mountPath: /dev/davinci1
                      - name: davinci-manager
                        mountPath: /dev/davinci_manager
                      - name: devmm-svm
                        mountPath: /dev/devmm_svm
                      - name: hisi-hdc
                        mountPath: /dev/hisi_hdc
                      - name: ascend-dcmi
                        mountPath: /usr/local/dcmi
                      - name: ascend-npu-smi
                        mountPath: /usr/local/bin/npu-smi
                      - name: ascend-driver-lib
                        mountPath: /usr/local/Ascend/driver/lib64
                      - name: ascend-driver-version
                        mountPath: /usr/local/Ascend/driver/version.info
                      - name: ascend-install-info
                        mountPath: /etc/ascend_install.info
                volumes:
                  - name: davinci0
                    hostPath:
                      path: /dev/davinci0
                  - name: davinci1
                    hostPath:
                      path: /dev/davinci1
                  - name: davinci-manager
                    hostPath:
                      path: /dev/davinci_manager
                  - name: devmm-svm
                    hostPath:
                      path: /dev/devmm_svm
                  - name: hisi-hdc
                    hostPath:
                      path: /dev/hisi_hdc
                  - name: ascend-dcmi
                    hostPath:
                      path: /usr/local/dcmi
                  - name: ascend-npu-smi
                    hostPath:
                      path: /usr/local/bin/npu-smi
                  - name: ascend-driver-lib
                    hostPath:
                      path: /usr/local/Ascend/driver/lib64
                  - name: ascend-driver-version
                    hostPath:
                      path: /usr/local/Ascend/driver/version.info
                  - name: ascend-install-info
                    hostPath:
                      path: /etc/ascend_install.info
        command: |
          source /usr/local/Ascend/ascend-toolkit/set_env.sh
          source /usr/local/Ascend/nnal/atb/set_env.sh
          pip install -e .
          VLLM_USE_MODELSCOPE=True pytest -s -v tests/e2e/offline_inference/test_qwen2_5_omni.py
        timeout_in_minutes: 60
        soft_fail: true

      - label: "NPU A2B3: Qwen3-Omni Offline Inference (2 cards)"
        agents:
          queue: "linux-aarch64-a2b3-gy006-test"
        plugins:
          - kubernetes#v1.0:
              image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
              podSpec:
                nodeSelector:
                  kubernetes.io/arch: arm64
                containers:
                  - name: test
                    volumeMounts:
                      - name: davinci0
                        mountPath: /dev/davinci0
                      - name: davinci1
                        mountPath: /dev/davinci1
                      - name: davinci-manager
                        mountPath: /dev/davinci_manager
                      - name: devmm-svm
                        mountPath: /dev/devmm_svm
                      - name: hisi-hdc
                        mountPath: /dev/hisi_hdc
                      - name: ascend-dcmi
                        mountPath: /usr/local/dcmi
                      - name: ascend-npu-smi
                        mountPath: /usr/local/bin/npu-smi
                      - name: ascend-driver-lib
                        mountPath: /usr/local/Ascend/driver/lib64
                      - name: ascend-driver-version
                        mountPath: /usr/local/Ascend/driver/version.info
                      - name: ascend-install-info
                        mountPath: /etc/ascend_install.info
                volumes:
                  - name: davinci0
                    hostPath:
                      path: /dev/davinci0
                  - name: davinci1
                    hostPath:
                      path: /dev/davinci1
                  - name: davinci-manager
                    hostPath:
                      path: /dev/davinci_manager
                  - name: devmm-svm
                    hostPath:
                      path: /dev/devmm_svm
                  - name: hisi-hdc
                    hostPath:
                      path: /dev/hisi_hdc
                  - name: ascend-dcmi
                    hostPath:
                      path: /usr/local/dcmi
                  - name: ascend-npu-smi
                    hostPath:
                      path: /usr/local/bin/npu-smi
                  - name: ascend-driver-lib
                    hostPath:
                      path: /usr/local/Ascend/driver/lib64
                  - name: ascend-driver-version
                    hostPath:
                      path: /usr/local/Ascend/driver/version.info
                  - name: ascend-install-info
                    hostPath:
                      path: /etc/ascend_install.info
        command: |
          source /usr/local/Ascend/ascend-toolkit/set_env.sh
          source /usr/local/Ascend/nnal/atb/set_env.sh
          pip install -e .
          VLLM_USE_MODELSCOPE=True pytest -s -v tests/e2e/offline_inference/test_qwen3_omni.py -m "npu"
        timeout_in_minutes: 60
        soft_fail: true

      - label: "NPU A2B3: Qwen3-TTS Online Serving (2 cards)"
        agents:
          queue: "linux-aarch64-a2b3-gy006-test"
        plugins:
          - kubernetes#v1.0:
              image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
              podSpec:
                nodeSelector:
                  kubernetes.io/arch: arm64
                containers:
                  - name: test
                    volumeMounts:
                      - name: davinci0
                        mountPath: /dev/davinci0
                      - name: davinci1
                        mountPath: /dev/davinci1
                      - name: davinci-manager
                        mountPath: /dev/davinci_manager
                      - name: devmm-svm
                        mountPath: /dev/devmm_svm
                      - name: hisi-hdc
                        mountPath: /dev/hisi_hdc
                      - name: ascend-dcmi
                        mountPath: /usr/local/dcmi
                      - name: ascend-npu-smi
                        mountPath: /usr/local/bin/npu-smi
                      - name: ascend-driver-lib
                        mountPath: /usr/local/Ascend/driver/lib64
                      - name: ascend-driver-version
                        mountPath: /usr/local/Ascend/driver/version.info
                      - name: ascend-install-info
                        mountPath: /etc/ascend_install.info
                volumes:
                  - name: davinci0
                    hostPath:
                      path: /dev/davinci0
                  - name: davinci1
                    hostPath:
                      path: /dev/davinci1
                  - name: davinci-manager
                    hostPath:
                      path: /dev/davinci_manager
                  - name: devmm-svm
                    hostPath:
                      path: /dev/devmm_svm
                  - name: hisi-hdc
                    hostPath:
                      path: /dev/hisi_hdc
                  - name: ascend-dcmi
                    hostPath:
                      path: /usr/local/dcmi
                  - name: ascend-npu-smi
                    hostPath:
                      path: /usr/local/bin/npu-smi
                  - name: ascend-driver-lib
                    hostPath:
                      path: /usr/local/Ascend/driver/lib64
                  - name: ascend-driver-version
                    hostPath:
                      path: /usr/local/Ascend/driver/version.info
                  - name: ascend-install-info
                    hostPath:
                      path: /etc/ascend_install.info
        command: |
          source /usr/local/Ascend/ascend-toolkit/set_env.sh
          source /usr/local/Ascend/nnal/atb/set_env.sh
          pip install -e .
          VLLM_USE_MODELSCOPE=True pytest -s -v tests/e2e/online_serving/test_qwen3_tts.py -m "npu"
        timeout_in_minutes: 60
        soft_fail: true

      - label: "NPU A2B3: Distributed Inference (4 cards)"
        agents:
          queue: "linux-aarch64-a2b3-gy006-test"
        plugins:
          - kubernetes#v1.0:
              image: "swr.cn-southwest-2.myhuaweicloud.com/modelfoundry/vllm-omni-ci-npu:${BUILDKITE_COMMIT}"
              podSpec:
                nodeSelector:
                  kubernetes.io/arch: arm64
                containers:
                  - name: test
                    volumeMounts:
                      - name: davinci0
                        mountPath: /dev/davinci0
                      - name: davinci1
                        mountPath: /dev/davinci1
                      - name: davinci2
                        mountPath: /dev/davinci2
                      - name: davinci3
                        mountPath: /dev/davinci3
                      - name: davinci-manager
                        mountPath: /dev/davinci_manager
                      - name: devmm-svm
                        mountPath: /dev/devmm_svm
                      - name: hisi-hdc
                        mountPath: /dev/hisi_hdc
                      - name: ascend-dcmi
                        mountPath: /usr/local/dcmi
                      - name: ascend-npu-smi
                        mountPath: /usr/local/bin/npu-smi
                      - name: ascend-driver-lib
                        mountPath: /usr/local/Ascend/driver/lib64
                      - name: ascend-driver-version
                        mountPath: /usr/local/Ascend/driver/version.info
                      - name: ascend-install-info
                        mountPath: /etc/ascend_install.info
                volumes:
                  - name: davinci0
                    hostPath:
                      path: /dev/davinci0
                  - name: davinci1
                    hostPath:
                      path: /dev/davinci1
                  - name: davinci2
                    hostPath:
                      path: /dev/davinci2
                  - name: davinci3
                    hostPath:
                      path: /dev/davinci3
                  - name: davinci-manager
                    hostPath:
                      path: /dev/davinci_manager
                  - name: devmm-svm
                    hostPath:
                      path: /dev/devmm_svm
                  - name: hisi-hdc
                    hostPath:
                      path: /dev/hisi_hdc
                  - name: ascend-dcmi
                    hostPath:
                      path: /usr/local/dcmi
                  - name: ascend-npu-smi
                    hostPath:
                      path: /usr/local/bin/npu-smi
                  - name: ascend-driver-lib
                    hostPath:
                      path: /usr/local/Ascend/driver/lib64
                  - name: ascend-driver-version
                    hostPath:
                      path: /usr/local/Ascend/driver/version.info
                  - name: ascend-install-info
                    hostPath:
                      path: /etc/ascend_install.info
        command: |
          source /usr/local/Ascend/ascend-toolkit/set_env.sh
          source /usr/local/Ascend/nnal/atb/set_env.sh
          pip install -e .
          VLLM_USE_MODELSCOPE=True pytest -s -v -m "distributed_npu"
        timeout_in_minutes: 90
        soft_fail: true
