name: 🤗 Support request for a new model
description: Submit a proposal/request for a new model support
title: "[New Model]: "
labels: ["new model"]

body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an issue, please make sure the issue hasn't been already addressed by searching through [the existing and past issues](https://github.com/vllm-project/vllm-omni/issues?q=is%3Aissue+sort%3Acreated-desc+).

      #### We also highly recommend you read the contributing guidelines first to understand how to add a new model.
- type: textarea
  attributes:
    label: The model to consider.
    description: >
      A huggingface url, pointing to the model, e.g. https://huggingface.co/openai-community/gpt2 .
  validations:
    required: true
- type: textarea
  attributes:
    label: The closest model vllm-omni already supports.
    description: >
      Here is the list of models already supported by vllm-omni. Which model is the most similar to the model you want to add support for?
- type: textarea
  attributes:
    label: What's your difficulty of supporting the model you want?
    description: >
      For example, any new operators or new architecture? Is it a multimodal model? Does it require special preprocessing?
- type: textarea
  attributes:
    label: Use case and motivation
    description: >
      What is the primary use case for this model? Why is it important to support in vllm-omni?
- type: markdown
  attributes:
    value: >
      Thanks for contributing 🎉!
- type: checkboxes
  id: askllm
  attributes:
    label: Before submitting a new issue...
    options:
      - label: Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://vllm-omni.readthedocs.io), which can answer lots of frequently asked questions.
        required: true
