ARG VLLM_ASCEND_IMAGE=swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/quay.io/ascend/vllm-ascend
ARG VLLM_ASCEND_TAG=v0.17.0rc1-linuxarm64
FROM ${VLLM_ASCEND_IMAGE}:${VLLM_ASCEND_TAG}

ARG APP_DIR=/vllm-workspace/vllm-omni
WORKDIR ${APP_DIR}

COPY . .

# 配置国内 GitHub 代理
RUN git config --global url."https://gh-proxy.test.osinfra.cn/https://github.com/".insteadOf "https://github.com/"

RUN export VLLM_OMNI_TARGET_DEVICE=npu && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib && \
    python3 -m pip install -U pip && \
    python3 -m pip install -v -e "/vllm-workspace/vllm-omni/[dev]" \
      --no-build-isolation \
      --index-url http://cache-service.nginx-pypi-cache.svc.cluster.local/pypi/simple \
      --trusted-host cache-service.nginx-pypi-cache.svc.cluster.local \
      --default-timeout=60

ENV VLLM_WORKER_MULTIPROC_METHOD=spawn

ENTRYPOINT []
