audio_vae:
  tod_vae_ckpt: /mnt/bn/hmbytenas/code/guoxu/ovi/ckpts/MMAudio/ext_weights/v1-16.pth
  bigvgan_vocoder_ckpt: /mnt/bn/hmbytenas/code/guoxu/ovi/ckpts/MMAudio/ext_weights/best_netG.pt
  mode: 16k
  need_vae_encoder: True 