# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

"""
Stage input processor for GLM-TTS two-stage pipeline.

Handles the transition from LLM stage (speech token generation)
to DiT stage (mel-spectrogram generation via flow matching).
"""

import torch
from vllm.inputs import TextPrompt

from vllm_omni.inputs.data import OmniTokensPrompt

# GLM-TTS special tokens
# These define the audio token range and boundaries
GLM_TTS_BOA_TOKEN_ID = 151329  # Beginning of Audio
GLM_TTS_EOA_TOKEN_ID = 151330  # End of Audio
GLM_TTS_AUDIO_TOKEN_START = 151936  # Start of audio token range
GLM_TTS_AUDIO_TOKEN_END = 184703  # End of audio token range (32768 tokens)


def extract_speech_tokens(token_ids: list[int]) -> list[int]:
    """
    Extract speech tokens from LLM output.

    Filters token IDs to only include valid audio tokens
    (between AUDIO_TOKEN_START and AUDIO_TOKEN_END).

    Args:
        token_ids: Raw token IDs from LLM output

    Returns:
        List of speech token IDs (normalized to 0-based indexing)
    """
    speech_tokens = []
    for token_id in token_ids:
        if GLM_TTS_AUDIO_TOKEN_START <= token_id <= GLM_TTS_AUDIO_TOKEN_END:
            # Normalize to 0-based index for the DiT model
            normalized_token = token_id - GLM_TTS_AUDIO_TOKEN_START
            speech_tokens.append(normalized_token)
    return speech_tokens


def llm2dit(
    stage_list,
    engine_input_source,
    prompt: OmniTokensPrompt | TextPrompt = None,
    requires_multimodal_data: bool = False,
):
    """
    Transform LLM outputs (speech tokens) into DiT stage inputs.

    This processor extracts speech tokens generated by the LLM stage
    and packages them for the DiT (flow matching) stage.

    Args:
        stage_list: List of all stages in the pipeline
        engine_input_source: List of upstream stage IDs to consume from
        prompt: Original prompt (may contain multimodal data)
        requires_multimodal_data: Whether to pass multimodal data downstream

    Returns:
        List of OmniTokensPrompt objects for the DiT stage
    """
    if not engine_input_source:
        raise ValueError("engine_input_source cannot be empty")

    source_stage_id = engine_input_source[0]
    if source_stage_id >= len(stage_list):
        raise IndexError(f"Invalid stage_id: {source_stage_id}")
    if stage_list[source_stage_id].engine_outputs is None:
        raise RuntimeError(f"Stage {source_stage_id} has no outputs yet")

    llm_outputs = stage_list[source_stage_id].engine_outputs
    dit_inputs = []

    if not isinstance(prompt, list):
        prompt = [prompt]

    # Extract multimodal data (speaker embeddings, etc.) from original prompts
    multi_modal_data = {}
    for llm_output, p in zip(llm_outputs, prompt):
        if p is not None and isinstance(p, dict):
            multi_modal_data[llm_output.request_id] = p.get("multi_modal_data", None)
        else:
            multi_modal_data[llm_output.request_id] = None

    for i, llm_output in enumerate(llm_outputs):
        output = llm_output.outputs[0]
        token_ids = output.token_ids

        # Extract speech tokens from LLM output
        speech_tokens = extract_speech_tokens(token_ids)

        if not speech_tokens:
            # If no speech tokens found, use the raw tokens
            # (LLM may not have started generating audio yet)
            speech_tokens = token_ids

        # Build additional information for DiT stage
        additional_information = {
            "speech_tokens": torch.tensor(speech_tokens, dtype=torch.long),
            "raw_token_ids": token_ids,
            "prompt_token_ids": llm_output.prompt_token_ids,
        }

        # Extract speaker embedding if available in multimodal output
        if hasattr(output, "multimodal_output") and output.multimodal_output:
            if "speaker_embedding" in output.multimodal_output:
                additional_information["speaker_embedding"] = output.multimodal_output["speaker_embedding"]
            if "latent" in output.multimodal_output:
                additional_information["llm_hidden_states"] = output.multimodal_output["latent"]

        dit_inputs.append(
            OmniTokensPrompt(
                prompt_token_ids=speech_tokens,
                additional_information=additional_information,
                multi_modal_data=(multi_modal_data.get(llm_output.request_id) if requires_multimodal_data else None),
                mm_processor_kwargs=None,
            )
        )

    return dit_inputs
